---
- name: Create users
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/users?token={{ login_token.json.authToken }}"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
    body: |
      {
        "username": "{{ item.key }}",
        "password": "{{ item.value['passwd'] }}",
        "attributes": {
          "disabled": "",
          "expired": "",
          "access-window-start": "",
          "access-window-end": "",
          "valid-from": "",
          "valid-until": "",
          "timezone": "Etc/GMT+0",
          "guac-full-name": "",
          "guac-organization": "",
          "guac-organizational-role": ""
        }
      }
  loop: "{{ users | dict2items }}"
  when:
    - item.key is defined
  register: result_task
  failed_when:
    - result_task.json.message is defined
    - '"already exists" not in result_task.json.message'

- name: Add users to their userGroups
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/users/{{ item.key }}/userGroups?token={{ login_token.json.authToken }}"
    method: PATCH
    body_format: json
    headers:
      Content-Type: application/json
    body: |
      [
        {
          "op": "add",
          "path": "/",
          "value": "{{ item.value['user_group'] }}"
        }
      ]
    status_code: [200, 204]
  loop: "{{ users | dict2items }}"
  when:
    - item.key is defined
