---
vms:
  hosts:
    podman-lab:
      ansible_host: 192.158.200.10
      ansible_ssh_private_key_file: ~/labs/podman-env/.vagrant/machines/podman-lab/libvirt/private_key
      ansible_user: vagrant
      guacamole_uri: "http://{{ ansible_host }}:8080/guacamole"
