---
- name: Create connections in Guacamole
  vars:
    filtered_parent: "{{ connectiongroups_tree.json.childConnectionGroups | selectattr('name', 'equalto', item.connection_group) | map(attribute='identifier') | first }}"
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/connections?token={{ login_token.json.authToken }}"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/' + item.connection_type + 'template.json.j2') }}"
  loop: "{{ connections }}"
  loop_control:
    loop_var: item
  register: result_task
  failed_when:
    - result_task.json.message is defined
    - '"already exists" not in result_task.json.message'
