---
- name: Get connectionGroups tree
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/connectionGroups/ROOT/tree?token={{ login_token.json.authToken }}"
    method: GET
    body_format: json
    headers:
      Content-Type: application/json
  register:
    connectiongroups_tree

- name: Create connections in Guacamole
  vars:
    filtered_parent: >-
      {{ connectiongroups_tree.json.childConnectionGroups
      | selectattr('name', 'equalto', item.connection_group)
      | map(attribute='identifier')
      | first
      }}
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/connections?token={{ login_token.json.authToken }}"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/' + item.connection_type + 'template.json.j2') }}"
  loop: "{{ connections }}"
  loop_control:
    loop_var: item
  register: result_task
  failed_when:
    - result_task.json.message is defined
    - '"already exists" not in result_task.json.message'

- name: Get connectionGroups updated tree
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/session/data/postgresql/connectionGroups/ROOT/tree?token={{ login_token.json.authToken }}"
    method: GET
    body_format: json
    headers:
      Content-Type: application/json
  register:
    connectiongroups_updatedtree

- name: Colect data to set permitions
  vars:
    filtered_connection_id: >-
      {{ connectiongroups_updatedtree.json.childConnectionGroups
      | map(attribute='childConnections')
      | flatten
      | selectattr('name', 'equalto', item.name)
      | map(attribute='identifier')
      | first
      }}
    filtered_connectiongroup: "{{ item.connection_group }}"
    filtered_usergroup: >-
      {{
        connectiongroups
        | selectattr('name', 'equalto', filtered_connectiongroup)
        | map(attribute='usergroups')
        | first
      }}
  ansible.builtin.include_tasks: set_connection_permition.yml
  loop: "{{ connections }}"
  loop_control:
    loop_var: item
