---
- name: Check if server is running
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}"
  register: server_running
  retries: 5
  delay: 5

- name: Debug content
  ansible.builtin.debug:
    msg: "{{ server_running }}"

- name: Get guacadmin token to init deploy config
  ansible.builtin.uri:
    url: "{{ guacamole_uri }}/api/tokens"
    method: POST
    body_format: form-urlencoded
    body:
      username: guacadmin
      password: guacadmin
  register: login_token
  when: server_running.status == 200
